public class HelloWorld {

   public static void greeting() {
      System.debug('Hello, World!');
   }
      public static void greeting2() {
         System.debug('Hello, World!');
       
   }
   public static void greeting3() {
      System.debug('Hello, World!');
    
}
   public static void greeting4() {
      System.debug('Hello, World! - 1');
 
}
   public static void greeting5() {
      System.debug('Hello, World! - 2');


}  public static void greeting6() {
      System.debug('Hello, World! - 9-4-2025');//hello world

}}

